version: '3.7'

services:
  rstudio:
    container_name: rstudio-docker
    image: rstudio-docker
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./data/:/home/rstudio/data
    env_file:
      - ./.env
    ports:
        - '8787:8787'
